### PR TITLE
fix(general): fix external scripts

### PR DESCRIPTION
**Pull request by serge1peshcoff**
apparently this file was required, so let it stay

### CODE REVIEW

**Comment by linuxbandit** [comment]
I thought you tested?

Yes that needs to stay and surely I am a bad reviewer, but again - I thought you tested it?

**Review by linuxbandit — APPROVED** [review]

**Comment by serge1peshcoff** [comment]
this one - yes

**Comment by linuxbandit** [comment]
I meant the previous one :p

**Comment by linuxbandit** [comment]
good anyway, i don't think there should be problems now

**Comment by serge1peshcoff** [comment]
it worked for me for whatever reason, that was weird. anyway I'll check if it'll work once more when deployed

**Pull request merged**
